[project]
name = "pyperformance_bm_crypto_pyaes"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "pyaes",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "crypto_pyaes"
