[project]
name = "pyperformance_bm_sqlglot"
requires-python = ">=3.7"
dependencies = [
    "pyperf",
    "sqlglot",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "sqlglot"
