[project]
name = "pyperformance_bm_list_sort"
requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "list_sort"
tags = "sorting"
extra_opts = ["list_sort"]
