[project]
name = "pyperformance_bm_toml_loads"
requires-python = ">=3.11"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "toml_loads"
tags = "serialize"
