exclude: ^pyperformance/data-files/
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        name: Run Ruff (lint)
        args: [--exit-non-zero-on-fix]
      - id: ruff-format
        name: Run Ruff (format)
        args: [--exit-non-zero-on-fix]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.21.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
