repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        name: Run Ruff (lint)
        args: [--exit-non-zero-on-fix]
        exclude: ^pyperformance/data-files/

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt
        exclude: ^pyperformance/data-files/

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        exclude: ^pyperformance/data-files/

