[project]
name = "pyperformance_bm_xdsl"
requires-python = ">=3.8"
dependencies = ["pyperf", "xdsl"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "xdsl"
