[project]
name = "pyperformance_bm_mako"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
     "Mako",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "mako"
tags = "template"
