[project]
name = "pyperformance_bm_sympy"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "sympy",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "sympy"
