[project]
name = "pyperformance_bm_coverage"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "coverage",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "coverage"
