[project]
name = "pyperformance_bm_networkx"
requires-python = ">=3.11"
dependencies = [
    "pyperf",
    "networkx",
]
urls.repository = "https://github.com/python/pyperformance"
dynamic = ["version"]

[tool.pyperformance]
name = "networkx_shortest_path"
extra_opts = ["shortest_path"]
