[project]
name = "pyperformance_bm_chameleon"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "Chameleon",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "chameleon"
tags = "apps"
