[project]
name = "pyperformance_bm_tomli_loads"
requires-python = ">=3.8"
dependencies = ["pyperf", "tomli"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "tomli_loads"
tags = "serialize"
