[project]
name = "pyperformance_bm_ctypes_argtypes"
requires-python = ">=3.7"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "ctypes_argtypes"
tags = "extension"
extra_opts = ["--argtypes"]
