[project]
name = "pyperformance_bm_ctypes"
requires-python = ">=3.7"
dependencies = ["pyperf", "setuptools"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "ctypes"
tags = "extension"
install_setup = true
