[project]
name = "pyperformance_bm_pickle_list"
requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "pickle_list"
tags = "serialize"
extra_opts = ["pickle_list"]
