[project]
name = "pyperformance_bm_unpickle"
requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "unpickle"
tags = "serialize"
extra_opts = ["unpickle"]
