[project]
name = "bm_tornado_http"
dependencies = [
    "tornado",
]

# XXX This should be inherited from metabase.
dynamic = [
  "name",
  "version",
]

[tool.pyperformance]
# "name" is set automatically.
metabase = ".."
