[project]
name = "pyperformance_bm_sphinx"
requires-python = ">=3.11"
dependencies = [
    "pyperf",
    "sphinx",
]
urls.repository = "https://github.com/python/pyperformance"
dynamic = ["version"]

[tool.pyperformance]
name = "sphinx"
tags = "apps"
