[project]
name = "pyperformance_bm_django_template"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "django",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "django_template"
tags = "template"
