[project]
name = "pyperformance_bm_tornado_http"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "tornado",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "tornado_http"
tags = "apps"
