[project]
name = "pyperformance_bm_docutils"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "docutils",
]
urls.repository = "https://github.com/python/pyperformance"
dynamic = ["version"]

[tool.pyperformance]
name = "docutils"
tags = "apps"
