[project]
name = "pyperformance_bm_html5lib"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "html5lib",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "html5lib"
tags = "apps"
