[project]
name = "bm_crypto_pyaes"
dependencies = [
    "pyaes",
]

# XXX This should be inherited from metabase.
dynamic = [
  "name",
  "version",
]

[tool.pyperformance]
# "name" is set automatically.
metabase = ".."
