[project]
name = "bm_html5lib"
dependencies = [
    "html5lib",
]

# XXX This should be inherited from metabase.
dynamic = [
  "name",
  "version",
]

[tool.pyperformance]
# "name" is set automatically.
metabase = ".."
