[project]
name = "bm_dulwich_log"
dependencies = [
    # optional?
    "dulwich",
]

# XXX This should be inherited from metabase.
dynamic = [
  "name",
  "version",
]

[tool.pyperformance]
# "name" is set automatically.
metabase = ".."
