[project]
name = "pyperformance_bm_genshi"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "Genshi",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "genshi"
tags = "template"
