[project]
name = "pyperformance_bm_dulwich_log"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "dulwich", # optional?
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "dulwich_log"
