name: ruff

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  ruff:
    name: Check code with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"
