name: Lint

on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  lint:
    name: Check code with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"
